Update prod builds
fragforce/fragforce.org pull request #609
Opened 2023-05-10 02:59 UTC by AevumDecessus

2023-05-10 17:49 UTC, gpmidi requested changes

2023-05-10 17:49 UTC, gpmidi commented on .github/workflows/prod-images.yaml
> +          push: true
Sure you wanna push PRs and such?

2023-05-10 19:51 UTC, AevumDecessus commented on .github/workflows/prod-images.yaml
> +          push: true
PRs aren't included in the "on" field, note this is scoped only to releases and pushes to master, while dev-images is scoped only to pushes to dev.

2023-05-10 19:52 UTC, AevumDecessus commented on .github/workflows/prod-images.yaml
> +          push: true
External PRs were removed entirely from the github actions workflows with this change, because they're hazardous, and because the GITHUB_TOKEN permissions are forcible set to read-only for external PRs with no way to override

2023-09-21 20:39 UTC, gpmidi approved these changes

2023-09-21 20:40 UTC, merged